package me.forty2.watloo.enums;

import lombok.Getter;

@Getter
public enum UserState {
    AWAITING_TERM_SELECTION,
    AWAITING_COURSE_NAME_INPUT,
    AWAITING_LOCATION_INPUT,
    AWAITING_DAY_SELECTION,
    AWAITING_TIME_INPUT,
    AWAITING_PROF_INPUT,
    AWAITING_RESTAURANT_REVIEW,
    AWAITING_VIEW_REVIEWS_OPTION,
    AWAITING_REVIEW_SEARCH_QUERY,
}
